name: Docker Image CI for GHCR

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:

jobs:
  build_and_publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and push image
        run: |
          docker login --username anilvmware --password ${{ secrets.GIT_PAT}} ghcr.io
          docker build . --tag ghcr.io/anilvmware/app-engine-image:test
          docker push ghcr.io/anilvmware/app-engine-image:latest

